platform :ios, '9.0'
#use_frameworks!
inhibit_all_warnings!
# pod的本地索引文件：~/Library/Caches/CocoaPods/search_index.json

#post_install do |installer|
#    
#    puts 'Determining pod project minimal deployment target'
#    
#    pods_project = installer.pods_project
#    deployment_target_key = 'IPHONEOS_DEPLOYMENT_TARGET'
#    deployment_targets = pods_project.build_configurations.map{ |config| config.build_settings[deployment_target_key] }
#    minimal_deployment_target = deployment_targets.min_by{ |version| Gem::Version.new(version) }
#    
#    puts 'Minimal deployment target is ' + minimal_deployment_target
#    puts 'Setting each pod deployment target to ' + minimal_deployment_target
#    
#    installer.pods_project.targets.each do |target|
#        target.build_configurations.each do |config|
#            config.build_settings[deployment_target_key] = minimal_deployment_target
#        end
#    end
#end

source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings! #inhibit_warnings参数能够有效的抑制CocoaPods引入的第三方代码库产生的warning。

target 'TSNotificationDemo' do
  pod 'CQDemoKit',                  '~> 0.5.10',     :subspecs => ['BaseVC']
    
  #pod 'TSDemo_DatePicker',          :path => '../'
  pod 'CJProtocolCenter',           :path => '../'
  pod 'CQModuleHelper',             :path => '../'
  pod 'CJProtocolCenter',           :path => '../'
  pod 'TSModulePublic',             :path => '../',     :subspecs => ['CJUserServicePublic', 'LoginModulePublic', 'OrderModulePublic']
  pod 'TSUserServiceImpl',          :path => '../'    # 用户数据管理模块
  pod 'TSLoginModuleImpl',          :path => '../'    # 登录模块
  pod 'TSOrderModuleImpl',          :path => '../'    # 订单模块
#  pod 'CQUserService_Login',        :source => 'https://gitee.com/dvlproad/dvlproadSpecs.git'
end

target 'TSNotificationDemoTests' do
    platform :ios, '9.0'
    
end

target 'TSNotificationDemoUITests' do
    platform :ios, '9.0'
    
end
